"""empty message

Revision ID: 389e9354daec
Revises: d333796edc66
Create Date: 2020-11-11 23:15:11.514246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389e9354daec'
down_revision = 'd333796edc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('time_zone', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'agent', ['time_zone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent', type_='unique')
    op.drop_column('agent', 'time_zone')
    # ### end Alembic commands ###
