"""empty message

Revision ID: 7875e8f4cb87
Revises: cb084a46f663
Create Date: 2020-11-07 15:48:11.910012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7875e8f4cb87'
down_revision = 'cb084a46f663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'option', 'interview', ['interview_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_column('option', 'interview_id')
    # ### end Alembic commands ###
