"""empty message

Revision ID: cb084a46f663
Revises: eab6707b1c2a
Create Date: 2020-11-07 15:15:59.307657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb084a46f663'
down_revision = 'eab6707b1c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'interview', ['interview_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'interview_id')
    # ### end Alembic commands ###
