"""empty message

Revision ID: e2c279ca17c0
Revises: 21f5d1bc6c5b
Create Date: 2020-11-03 17:53:19.833319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c279ca17c0'
down_revision = '21f5d1bc6c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
